# Project Information
sonar.projectKey=node-app
sonar.projectName=Node Application
sonar.projectVersion=1.0

# Source Code
sonar.sources=.

# Test Folder
sonar.tests=tests

# JavaScript Files
sonar.exclusions=node_modules/**,coverage/**,reports/**,tests/**

# Include only JS tests
sonar.test.inclusions=tests/**/*.js

sonar.sourceEncoding=UTF-8
