# Project Information
sonar.projectKey=node-app
sonar.projectName=Node Application
sonar.projectVersion=1.0

# Source Code
sonar.sources=.

# Test Folder
sonar.tests=tests

# JavaScript Files
sonar.inclusions=**/*.js

# Exclude unnecessary folders
sonar.exclusions=node_modules/**,coverage/**,reports/**

# Encoding
sonar.sourceEncoding=UTF-8
