name: Setup for Node.js Application for Docker 

on:
    workflow_dispatch:

jobs:
    build-steps-sample:
        runs-on: ubuntu-latest
        
        steps:
          - name: Check the Code
            run: echo "To Check the Code"

          - name: Setup Environment for NODE APP
            run: echo ""

          - name: Build and Test App
            run: echo ""

          - name: Upload Test Samples
            run: echo ""

    run-workflow:
        runs-on: ubuntu-latest
        needs: build-steps-sample
        
        steps:
          - name: Check the Code
            uses: actions/checkout@v6

          - name: Setup Environment for Node APP
            uses: actions/setup-node@v6
            with:
                node-version: 24

                
    docker-build-image:
        runs-on: ubuntu-latest
        needs: run-workflow
        
        steps:
          - name: Check the Code
            uses: actions/checkout@v6

          - name: Setup Environment for Node APP
            uses: actions/setup-node@v6
            with:
                node-version: 24

          - name: Docker Login
            uses: docker/login-action@v4
            with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}

          - name: To Build and Push Docker Images
            uses: docker/build-push-action@v7
            with:
                context: docker/app1-hello/node
                push: true
                tags: |
                    ${{ vars.DOCKERHUB_USERNAME }}/hello-node:latest
                    ${{ vars.DOCKERHUB_USERNAME }}/hello-node:${{ github.sha }}

          - name: Trigger Jenkins
            run: |
                curl -X POST \
                "${{ vars.JENKINS_URL }}/job/jenkins-for-hello/buildWithParameters?token=${{ secrets.JENKINS_TRIGGER_TOKEN }}&BRANCH=main" \
                --user "${{ vars.JENKINS_USER }}:${{ secrets.JENKINS_PASSWORD }}"

                    







