name: Pipeline for jenkins 

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v4
          - name: Script for Second Pipeline
            run: echo "My Second Pipeline runs successfully!"

          - name: Check Jenkins Connection
            run: |
                curl -v "${{ vars.JENKINS_URL }}/login"