name: Pipeline for jenkins 

on:
    push:

jobs:
    build:
        runs-on: self-hosted
        
        steps:
          - uses: actions/checkout@v4
          - name: Script for Second Pipeline
            run: echo "My Second Pipeline runs successfully!"

          - name: Check Jenkins Connections 
            run: |
                echo "URL: ${{ vars.JENKINS_URL }}"
                echo "USER: ${{ vars.JENKINS_USER }}"